import {
  Apple,
  Baby,
  Backpack,
  Banknote,
  BedDouble,
  Beer,
  Bike,
  Bitcoin,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  CakeSlice,
  Calendar,
  Camera,
  Candy,
  Car,
  CarFront,
  CarTaxiFront,
  Carrot,
  Cat,
  ChartLine,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  Coins,
  CookingPot,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Guitar,
  HandCoins,
  HandHeart,
  Heart,
  House,
  IceCreamCone,
  KeyRound,
  Landmark,
  Laptop,
  Lightbulb,
  type LucideIcon,
  Luggage,
  Mail,
  Map as MapIcon,
  Milk,
  Mountain,
  Music,
  Palette,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Printer,
  Receipt,
  Sandwich,
  School,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Ship,
  Siren,
  Smartphone,
  Sofa,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  SquareParking,
  Star,
  Stethoscope,
  Tag,
  Tent,
  Ticket,
  ToyBrick,
  TrainFront,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Watch,
  Wheat,
  Wifi,
  Wine,
  Wrench,
} from "lucide-react";

/**
 * The category icon system's LIGHT render path (#80 chunk 4). Categories store
 * a lucide icon name in `Category.icon`; the picker can choose from the entire
 * lucide set (see `iconCatalog.ts`).
 *
 * This module bundles only a curated ~100-icon set — the seed categories plus
 * common budget concepts — so the broad render path (Pulse cards, pills, etc.)
 * stays tiny and renders instantly. A category whose chosen icon is outside
 * this set renders via the lazily-loaded catalogue (`CategoryIcon` →
 * `LazyLucideIcon`), so every icon is still supported, just deferred.
 */

// Curated icons available for instant, statically-bundled rendering.
const RENDER_ICONS: Readonly<Record<string, LucideIcon>> = {
  ShoppingCart,
  Utensils,
  Pizza,
  Sandwich,
  Soup,
  CakeSlice,
  IceCreamCone,
  Candy,
  Apple,
  Carrot,
  CookingPot,
  Coffee,
  Beer,
  Wine,
  Milk,
  Wheat,
  Fuel,
  Car,
  CarFront,
  TrainFront,
  Bus,
  Bike,
  CarTaxiFront,
  Plane,
  Ship,
  SquareParking,
  House,
  Building2,
  KeyRound,
  Lightbulb,
  Droplet,
  Flame,
  Wifi,
  Smartphone,
  Wrench,
  Sofa,
  Sprout,
  SprayCan,
  ShoppingBag,
  Shirt,
  Footprints,
  Backpack,
  Gem,
  Watch,
  Glasses,
  Sparkles,
  Scissors,
  Gift,
  Stethoscope,
  Pill,
  Heart,
  Dumbbell,
  Trophy,
  Clapperboard,
  Popcorn,
  Tv,
  Music,
  Gamepad2,
  BookOpen,
  Camera,
  Palette,
  Ticket,
  Guitar,
  GraduationCap,
  School,
  Briefcase,
  Laptop,
  Printer,
  Mail,
  Calendar,
  Banknote,
  Coins,
  PiggyBank,
  Landmark,
  TrendingUp,
  ChartLine,
  CreditCard,
  Wallet,
  HandCoins,
  Bitcoin,
  Receipt,
  ShieldCheck,
  HandHeart,
  Siren,
  PawPrint,
  Dog,
  Cat,
  Baby,
  ToyBrick,
  Users,
  Umbrella,
  BedDouble,
  Luggage,
  Map: MapIcon,
  Tent,
  Mountain,
  Star,
  Tag,
  CircleDollarSign,
};

/** Fallback for a missing/unknown icon — a neutral money glyph, never blank. */
export const DEFAULT_CATEGORY_ICON: LucideIcon = CircleDollarSign;

/** A curated icon by name, if it's in the statically-bundled set. */
export function iconByName(name: string | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return RENDER_ICONS[name];
}

/**
 * Legacy/seed emoji → lucide icon name. Only consulted when a category has no
 * `icon` (i.e. it predates the icon field). Every target is in `RENDER_ICONS`
 * so seed/legacy categories always render instantly.
 */
const EMOJI_ICON_NAMES: Readonly<Record<string, string>> = {
  // Seed categories
  "🛒": "ShoppingCart",
  "🍔": "Utensils",
  "⛽": "Fuel",
  "💡": "Lightbulb",
  "🏠": "House",
  "🎬": "Clapperboard",
  "🛍️": "ShoppingBag",
  "✈️": "Plane",
  "🏦": "Landmark",
  "📈": "TrendingUp",
  "🏖️": "Umbrella",
  "💼": "Briefcase",
  "📊": "ChartLine",
  // Common others
  "☕": "Coffee",
  "🍺": "Beer",
  "🍷": "Wine",
  "🍕": "Pizza",
  "🍜": "Soup",
  "🍰": "CakeSlice",
  "🍦": "IceCreamCone",
  "🍎": "Apple",
  "🥕": "Carrot",
  "🥦": "Carrot",
  "🥛": "Milk",
  "🌾": "Wheat",
  "🚗": "Car",
  "🚙": "CarFront",
  "🚆": "TrainFront",
  "🚌": "Bus",
  "🚲": "Bike",
  "🚕": "CarTaxiFront",
  "🚢": "Ship",
  "🅿️": "SquareParking",
  "🏡": "House",
  "🏢": "Building2",
  "🔑": "KeyRound",
  "💧": "Droplet",
  "🔥": "Flame",
  "🌐": "Wifi",
  "📱": "Smartphone",
  "🔧": "Wrench",
  "🛋️": "Sofa",
  "🌱": "Sprout",
  "🧴": "SprayCan",
  "👕": "Shirt",
  "👟": "Footprints",
  "🎒": "Backpack",
  "💍": "Gem",
  "⌚": "Watch",
  "👓": "Glasses",
  "💄": "Sparkles",
  "💈": "Scissors",
  "🎁": "Gift",
  "🩺": "Stethoscope",
  "💊": "Pill",
  "❤️": "Heart",
  "🏋️": "Dumbbell",
  "🏆": "Trophy",
  "🍿": "Popcorn",
  "📺": "Tv",
  "🎵": "Music",
  "🎮": "Gamepad2",
  "📚": "BookOpen",
  "📷": "Camera",
  "🎨": "Palette",
  "🎟️": "Ticket",
  "🎸": "Guitar",
  "🎓": "GraduationCap",
  "🏫": "School",
  "💻": "Laptop",
  "🖨️": "Printer",
  "📧": "Mail",
  "📅": "Calendar",
  "💵": "Banknote",
  "🪙": "Coins",
  "💰": "PiggyBank",
  "💳": "CreditCard",
  "👛": "Wallet",
  "💸": "HandCoins",
  "₿": "Bitcoin",
  "🧾": "Receipt",
  "🛡️": "ShieldCheck",
  "💝": "HandHeart",
  "🚨": "Siren",
  "🐾": "PawPrint",
  "🐶": "Dog",
  "🐱": "Cat",
  "👶": "Baby",
  "🧸": "ToyBrick",
  "👨‍👩‍👧": "Users",
  "🏨": "BedDouble",
  "🧳": "Luggage",
  "🗺️": "Map",
  "⛺": "Tent",
  "🏔️": "Mountain",
  "⭐": "Star",
  "🏷️": "Tag",
  "🪣": "CircleDollarSign",
};

/**
 * The statically-available icon for a category, if any. Prefers the stored
 * `icon` name, then the legacy emoji mapping. Returns `undefined` when the
 * chosen icon lives outside the curated set — the caller (`CategoryIcon`) then
 * defers to the lazily-loaded full catalogue.
 */
export function staticIconFor(category: {
  icon?: string;
  emoji?: string;
}): LucideIcon | undefined {
  return (
    iconByName(category.icon) ??
    iconByName(category.emoji ? EMOJI_ICON_NAMES[category.emoji] : undefined)
  );
}
